apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - ../base

patches:
  - path: configmap.patch.yaml
  - path: certificate.patch.yaml
  - path: gateway.patch.yaml
  - path: httproute.patch.yaml

replicas:
  - name: developer-portal
    count: 2

images:
  - name: registry.carverauto.dev/serviceradar/developer-portal
    newTag: latest
