apiVersion: v1
kind: ConfigMap
metadata:
  name: developer-portal-config
  namespace: serviceradar-developer
data:
  PHX_HOST: developer-staging.serviceradar.cloud
  PGHOST: developer-portal-pg-rw.serviceradar-developer-staging.svc.cluster.local
