apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: developer-portal-edge
  namespace: serviceradar-developer
spec:
  ipFamily: DualStack
  logging:
    level:
      default: warn
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        patch:
          type: StrategicMerge
          value:
            spec:
              template:
                spec:
                  containers:
                    - name: envoy
                      livenessProbe:
                        timeoutSeconds: 5
                      readinessProbe:
                        failureThreshold: 3
                        timeoutSeconds: 5
                      startupProbe:
                        timeoutSeconds: 5
                    - name: shutdown-manager
                      livenessProbe:
                        timeoutSeconds: 5
                      readinessProbe:
                        timeoutSeconds: 5
                      startupProbe:
                        timeoutSeconds: 5
      envoyService:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/address-pool: k3s-pool
        patch:
          type: StrategicMerge
          value:
            spec:
              ipFamilies:
                - IPv4
                - IPv6
              ipFamilyPolicy: PreferDualStack
